#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

for file in ${XDG_CONFIG_HOME:-~/.config}/bash/*.bash; do
	source $file
done

# >>> Added by cnchi installer
BROWSER=/usr/bin/firefox
EDITOR=/usr/bin/nvim

